language: node_js
node_js:
- '7'
deploy:
  provider: npm
  email: larry.eliemenye@gmail.com
  on:
    branch: master
    tags: true
  api_key:
    secure: flq4YLM40h3XAyHniI/t7XxnAu0wbRsioX08RWau26VDII9EbFcuBGNlHlvZFgYCWQ1oDe1bMlDc7LJ6YyUgkD+X56dtfjef6QFJ5kZA599WVAxVwqexCeJsrMMoJHsSFSPKWR8MTAtw2xZX5xrhpnHzhPjF+Oo451H3KCg0biGQDzzGexpnRoki0JxcFktEGxs1+iGjEMDVeTRPFk1FtfV6KJ0XORmpMSNeBJao9kZCl06g8tiARu/riECYU/4219R0NGYP3clvijGtqAYrnwGagEe/M6Mg4KhgnfJjFBSP3k91m8JlIPJAOasm25q7OhTK+ocLxGK67XnkiQvki72xVG4Ny162uIKKoJYjt+6aErNAHWIEHTX8/0Y4KJlDcdbPeviR7OFxuue+Idbi+TacDB1SbkioLkMpb/6g6F3QmyQPfA76pFqilRpULNu5hJO8WJMKTUzmEQ7wJaSFeumAXuudWPz/dFy/FvQ+Oe2c7hiV/eW5V2goxqxusrydVgcTXG/1Fw91pQ+ibqUmmYMpwPqutHCNvLdl+muYm2ta5it/YAOTThMZU8MmSfcdi65J+zDAb2cJ3gkXCekEJ6x76VI4MduCZJBFLZ1YBVgyAVYybnBHgZzhPsmXWyvYDiSMVSl7LZtlrsofK+GB4XXARBXue5rQYS2ZH7LVG2k=
